name: movies
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  introduction_screen: ^3.1.14
  shared_preferences: ^2.4.0
  carousel_slider: ^5.0.0
  video_player: ^2.9.2
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.17
  url_launcher: ^6.2.5
  flutter_bloc: ^8.1.4
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  connectivity_plus: ^6.1.4
  cloud_firestore: ^5.4.4
  path_provider: ^2.1.1
  dio: ^5.3.2
  permission_handler: ^11.0.1
  sqflite: ^2.3.0
  flutter_cache_manager: ^3.3.1
  speech_to_text: ^7.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/images/Forgot.png
    - assets/images/Empty.png
    - assets/model_ai/
    - assets/Splash Screen.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
